apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: release-2.16  # ACM version channel
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # ensure ACM stays on 2.16.0
  installPlanApproval: Manual
  startingCSV: advanced-cluster-management.v2.16.0
# Uncomment this section for placement on infra nodes
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
